version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - chmod +x build-img.sh push-img.sh
      - ./build-img.sh

  build:
    commands:
      - ./push-img.sh